[package]
name = "AMM"
edition = "2024.beta"

[dependencies]
SuiProver = { git = "https://github.com/asymptotic-code/sui-prover.git", subdir = "packages/sui-prover", rev = "main", override = true }

[addresses]
amm = "0x0"
